export const ADD_TO_CART = 'ADD_TO_CART';
export const POP_FROM_CART = 'POP_FROM_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const PRODUCTS = 'PRODUCTS';
export const PRODUCTS_SEARCH = 'PRODUCTS_SEARCH';
export const PRODUCTS_SORT = 'PRODUCTS_SORT';
export const PRODUCTS_FILTER = 'PRODUCTS_FILTER';


